### PR TITLE
EMT Buff

### PR DESCRIPTION
**Pull request by SanMan911**
Buffed the solars to 10x as discussed with @DreamMasterXXL earlier. Could take effect when IC2 recipes are changed accordingly.

### CODE REVIEW

**Comment by Technus** [comment]
Even if that would not work since the solars can output max 2048 due to tier limit somewhere.

**Comment by Technus** [comment]
Power gen rebalance - soon(tm)

**Comment by Dream-Master** [comment]
When i am nerfing this mod we have to look into it again. Maybe have to change code wise.

**Comment by Dream-Master** [comment]
I will go over it soon

**Pull request closed without merging**
