### PR TITLE
add milk radiation quest

### PR DESCRIPTION
**Pull request by DualBallers**
gave it a shot of adding this quest https://github.com/GTNewHorizons/NewHorizons/issues/3607

### CODE REVIEW

**Comment by Dream-Master** [comment]
added allready manually

**Comment by DualBallers** [comment]
I think this merge broke the quest line 2.0.6.0 here...
image

**Comment by Dream-Master** [comment]
did you reload the quests?

**Comment by DualBallers** [comment]
Yes, of course

**Comment by Dream-Master** [comment]
@DualBallers what is broken here? i dont undertsnad this pic

**Comment by DualBallers** [comment]
Shouldn't there be a quest line between the machine hull and the radiation suit? It was there in previous version.
(the pic is taken in the quest book admin mode)

**Comment by Dream-Master** [comment]
yes ther was a quest. Is it vanish ?

**Comment by DualBallers** [comment]
No, there was no quest before, screen shot from 2.0.5.x here
image

I made the commit above for a quest in between, but I don't know if you included it.

**Comment by Dream-Master** [comment]
will check

**Pull request closed without merging**
