### PR TITLE
Quests should check NBT for items that really matter

### PR DESCRIPTION
**Pull request by DeForce**

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
@DeForce did you check NBT on ANY GT Block or tool? if so, that will break the quest

**Comment by DeForce** [comment]
It is actually simpler.
No NBT data in task items - we don't check for NBT.
We have NBT data in tasks - we check NBT

**Comment by DeForce** [comment]
and yes, I did manually check couple quests, they did work.

**Comment by bartimaeusnek** [comment]
sometimes there is NBT data on items, where it does not matter, i.e. motors, if we check for the NBT there, only the person who wrote/edited the quest will be able to complete it. same goes for a lot of BW/GT/GT++/TT machines, and some Thaumcraft stuff aswell. But we will see on Zeta how it goes.. just fyi

**Comment by DeForce** [comment]
This is a good point, let me do a recheck, but I think if I find that data - we better remove it from task data cause it's not really valid data point for a quest

**Pull request merged**
