### PR TITLE
Move AE down to HV

### PR DESCRIPTION
**Pull request by Methes**
Titanium changed to Vibrant Alloy. Molecular Assembler still needs EV Assembler.

### CODE REVIEW

**Comment by mitchej123** [comment]
Personally I'd like to see just the basics (storage) available at HV.  I'd rather everything else (autocrafting, quantum tunnels, etc) stay at their current tier.

I'd rather throw titanium (which I have a lot of) at those than vibrant alloy (which I have almost none of)

**Comment by bigbass1997** [comment]
I don't know how this would play out exactly, but perhaps think about leaving in the titanium recipes, and making separate recipes that use vibrant alloy (tho perhaps even more expensive than just the alloy). This way once the player gets access to Titanium, it becomes a lot easier to make more AE stuff, and thus there's still a driving force to progress.

**Comment by mitchej123** [comment]
> but perhaps think about leaving in the titanium recipes, and making separate recipes that use vibrant alloy (tho perhaps even more expensive than just the alloy)

I'm a fan; then it doesn't break existing setups

**Comment by bartimaeusnek** [comment]
As i have already stated under the issue, i dont think we should move AE2 down a tier, simply because it encurages the use of storage interfaces on drawers, which hughly impacts performance. If we want to downtier AE2, we should definitely downtier the storage Cells aswell.

**Comment by mitchej123** [comment]
Are we ignoring #votes then?

image

**Comment by mitchej123** [comment]
If we're not going to use the results from #vote... let's remove the channel or make it 100% clear with a sticky/admin post they're "suggestions only" and the staff may choose to do something completely different at their own whim.

**Comment by botn365** [comment]
the only tings that should be down tierd is the energy acepter and the interface tis will alow for a smal ae network in HV

**Comment by Dream-Master** [comment]
i am agianst a complete change too. Small changes on the first items you need for ae is good idea . Make a small ae in hv and upgrade/make it bigger  it in ev.

**Comment by Dream-Master** [comment]
and btw why vibrant alloy ??? why not stainless steel or another material

**Comment by ScriptedPiky** [comment]
> and btw why vibrant alloy ??? why not stainless steel or another material

So Vibrant Alloy was my idea in the #github-discussion because it's a more 'difficult' material in the HV tier. Why not Stainless you ask? Well, Stainless Steel is obtained right as you progress into HV. So theoretically, the player can directly skip towards the beginning of AE with beginning HV level materials.

However, due to Vibrant Alloy now being the case, you now require three important things: Cleanroom, Freezer, and several other requirements before progressing onward into AE.

**Comment by observeroftime02** [comment]
I would honestly prefer Vibrant Alloy, because it's a more complex material to obtain than simply stainless steel. The making of Vibrant Alloy is a bit more involved than Stainless. 

Look at this:
image

**Comment by mitchej123** [comment]
as long as the titanium recipes stay whatever we do...

**Comment by Dream-Master** [comment]
My Plan is to change only the 4 or 5 basic componen items for make a poor man's ae like power acceptor rack chest and cables.

**Comment by ljjmrlion** [comment]
AE storage controller on a drawer controller sounds really nice for HV.

**Comment by Dream-Master** [comment]
If i tiere them down why not put recipes in 9x9 grid of Avaritia table. Make recipes a bit more complex like 4x4 or 3x4 crafting.

**Comment by Dream-Master** [comment]
or assembler recipes

**Comment by shawnbyday** [comment]
This will also require updating the quests so that it has a new "requirement" for unlocking the AE tab.

**Comment by Dream-Master** [comment]
i dont merge this. I close this now. We need a new and better concept for it.

**Pull request closed without merging**
