### PR TITLE
spelling errors

### PR DESCRIPTION
**Pull request by Auge103**
Corrected a sentence that gave me anxiety just by looking at it

### CODE REVIEW

**Comment by repo-alt** [comment]
I think the mention of a Wither right in the first line was, well, instructive, regardless of the Germanglish grammar.

**Comment by Dream-Master** [comment]
@Auge103 yes add back wither warning like @repo-alt said. After this I will merge it.
@Auge103 and thanks

**Comment by Dream-Master** [comment]
@Auge103 any news here ?

**Comment by Dream-Master** [comment]
@Auge103 any news if not i close this.

**Pull request closed without merging**
