### PR TITLE
Avaritia part 2 + bugfix

### PR DESCRIPTION
**Pull request by Ethryan**
Finally done with extreme crafting, 
Found a bug in thaumic bases and fixed it for now.

Added config for GT Vein Locator (Made it so that you can't find them in chests).

### CODE REVIEW

**Comment by Dream-Master** [comment]
Please remove gt vein locator cfg because I change things there all ready. Thanks @Ethryan

**Comment by Ethryan** [comment]
done

**Comment by Dream-Master** [comment]
@Ethryan Why you made the Tome easier. I make the recipe because the original recipe was to cheap.

**Comment by Dream-Master** [comment]
If i got time time i will check both recipe and lwt you know if i accept the new recipe.

**Comment by Dream-Master** [comment]
@Ethryan thanks

**Pull request merged**
