### PR TITLE
WT script

### PR DESCRIPTION
**Pull request by Prometheus0000**
Script for Warp Theory changes, see #5643.

### CODE REVIEW

**Comment by yukieiji** [comment]
I felt that the amount of Essentia was a little small (1.25 times may be just right)
Because with Essentia Locus and Infusion Claw, Infusion can be automated at an early stage and could be the main method of removing warp.

**Comment by Prometheus0000** [comment]
The Locus sounds like a pain to build/use. Have you actually set this kind of thing up for infusion? I think most people would just wait for TE. Keep in mind you still have to wait for the items to smelt down, plus getting them in the first place. I'm not sure you should assume people have either of the advanced furnaces. And doesn't it take another second for every 2-3 essentia to the time to complete? Does it need to be longer when you need to make a bunch? I'm not balancing for WAs here.

That said, if other people agree, then that's fine.

**Comment by Prometheus0000** [comment]
Also, the difficulty is more in the items than the essentia anyway.

**Comment by Prometheus0000** [comment]
@Dream-Master, do you think you could change the 3 instances of 'Pure? Tear' to 'Impure Tear'? They decided to change it to that in the other PR https://github.com/GTNewHorizons/WarpTheory/pull/2. It seems silly just to make another PR just for that.

**Comment by Dream-Master** [comment]
@Prometheus0000 make a new one. Thanks

**Comment by Dream-Master** [comment]
Done with https://github.com/GTNewHorizons/NewHorizons/commit/972ebd5078ac2534fe99cd0f247af713d0295811

**Pull request merged**
