### PR TITLE
Add Sky Stone to Mark of the Falling Tower ritual from blood magic #4794

### PR DESCRIPTION
**Pull request by Dream-Master**
suggested change from @Prometheus0000

### CODE REVIEW

**Comment by Prometheus0000** [comment]
It seems there's some more items on the WoS blacklist for some reason? I'm not sure how those got there? Or did you add them?

**Comment by Dream-Master** [comment]
sorry post in wrong branch

**Comment by Prometheus0000** [comment]
And like I said on discord, without the AE2.zs file change, the Skystone won't show up on the meteor.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/de03d9aa7efb948bea6800dc7ab6caefc6ab73b0

**Comment by Dream-Master** [comment]
this is on top @Prometheus0000

**Comment by Ethryan** [comment]
This looks interesting.

**Comment by Prometheus0000** [comment]
From the discord there's a general consensus that it's good, but the Nq+ should be removed (the oreBlackgraniteNaquadahEnriched and the 1 on the line after.) 

Also, while you're at it, could you change I:Skeleton=10 to 500? This is how much blood you get from using the dagger on mobs, and all the other skeleton types are 500.

**Comment by Dream-Master** [comment]
@Prometheus0000 feel free to change the pull and let me know when I can merge it.

**Comment by Dream-Master** [comment]
@Prometheus0000 what ? a skeleton has no blood

**Comment by mitchej123** [comment]
It's life essence... Not blood.

**Comment by Dream-Master** [comment]
skeleton have no life also

**Comment by mitchej123** [comment]
Untrue. They have unnatural life.  Plenty of essence to be stolen from them

**Comment by Prometheus0000** [comment]
The other skeletons (from special mobs) are at 500. Changing it from 500 to be less changes the balance of BM to make it harder when it's already been made harder (increased slate and other craft costs). Keep in mind that like GT, if you run out of blood in the altar in the middle of a craft you rapidly lose progress. So skeletons being less if you use a mob farm to get blood makes it harder to to do the over 10000 (what an altar contains) crafts. And the blood letter's pack can't add to an altar in progress.

Anyways, I think skeletons having LP or not is a different discussion, and the meteor itself is ready to merge, yeah? Unless you're still reading the Discord history or talking to the other staff members about it?

**Comment by mitchej123** [comment]
Dream.  Please play though blood magic if you haven't, and then Nerf it... It's way over nerfed right now

**Comment by Prometheus0000** [comment]
I don't disagree, but doesn't that discussion belong on #4843? Me and N20/piky also discussed it some on discord if you want to read that.

**Pull request merged**
