### PR TITLE
Infernal Mobs edits

### PR DESCRIPTION
**Pull request by damug**
Remove choking, ninja, and vengeance effects from infernal mobs.

https://github.com/GTNewHorizons/NewHorizons/issues/2176

### CODE REVIEW

**Comment by Dream-Master** [comment]
If we disable all mobs type we can remove to mod. I like to see fixes in code.

**Comment by richardhendricks** [comment]
@Dream-Master We don't currently have a repo for Infernal Mobs under GTNewHorizons. Can you create one?

**Comment by Dream-Master** [comment]
I will do asap

**Comment by Dream-Master** [comment]
@richardhendricks done

**Comment by draknyte1** [comment]
Fixing the Ninja modifier should be easy..
Vanilla has methods to check for a valid mob spawn area, which in this instance should be used to check for valid teleport areas. Look into things like the Zombie aid event for how the extra zombies are spawned in near the original and the logic is about the same.

**Comment by Dream-Master** [comment]
Ok sounds cool. Hope we get a fix soon 😁

**Comment by Namikon** [comment]
Closing this as the effects will not be disabled, but fixed in code to function properly

**Pull request closed without merging**
