### PR TITLE
Add Sandstone Crafting

### PR DESCRIPTION
**Pull request by deeplyarnab**
and fix spelling mistakes

### CODE REVIEW

**Comment by Dream-Master** [comment]
I will check the Sandstone recipe via Compressor not sure why this is off.
Please push new stuff to 1.0.7.8 Branch because this will be the next update.

**Comment by deeplyarnab** [comment]
ok

**Comment by Goofyschooler** [comment]
If you put sand in a compressor it just makes compressed sand.

**Comment by Dream-Master** [comment]
compressed sand ?

**Comment by Goofyschooler** [comment]
Is like compressed cobblestone. Please do not put single compressed sand in the implosion. It's an absolute waste of tnt and material.

**Comment by Dream-Master** [comment]
no i will take it back to the compressor

**Comment by deeplyarnab** [comment]
i'll remove the recipe and instead push spell fixes to 1.0.7.8

**Comment by Dream-Master** [comment]
ok yes good idea thanks

**Pull request closed without merging**
