### PR TITLE
Issue 3808 - Quest ID 1156 Iron Tipped Bolts Not Completing.

### PR DESCRIPTION
**Pull request by shawnbyday**
#3808 Fixed the quest so it will now complete correctly and I updated the quest text to reflect making the bolts with the smeltery instead of the fluid solidifier.

I've tested this in my locale (US) but I'm wondering if someone else can test in a different locale? I'm not sure it matters but quest detection was sort of odd.

What ended up fixing this was to set the quest to ignore NBT. Based on the diff below it looks like I changed other things when I didn't and I'm wondering if that is a localization thing (hence my above comment).

If you have any questions let me know.

### CODE REVIEW

**Comment by shawnbyday** [comment]
Yea let me look at this again when I get a chance either later tonight after work or tomorrow sometime. I usually make my changes to the DefaultQuest.json in a text editor as opposed to the BQ admin interface. The question marks probably showed up because I did it from in game.

Based on the NBT format https://minecraft.gamepedia.com/NBT_format I didn't see anything that would cause an issue but I'll definitely defer to your hesitation on that. Has ignoring NBT for quests caused issues in the past? I'll maybe grab an NBT editor and look at my file to see exactly what the difference is that causes the quest to not complete just to be a little more thorough.

**Comment by Dream-Master** [comment]
you can look into the nbt tag in edit mode and check it.

**Comment by shawnbyday** [comment]
I'm still working on this. I spent most of my weekend at work. I did review the NBT data on the quest but the only thing that was different was my change saying to ignore. I was rushed though so i want to look again and I should be able to get that done tonight after work.

**Comment by shawnbyday** [comment]
@Dream-Master the only way I'm able to get this to complete is by setting it to ignore NBT data. I even tried tossing the bolts on the ground and picking them back up.

You can maybe close my pull request if you'd like maybe someone else has some other things they can try on this. I believe I have it as an open issue as well.

**Comment by Dream-Master** [comment]
yea i fix it now

**Pull request closed without merging**
